import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ProviderSetting } from '@/settings';
import { UiSidebarLayout } from '@/layout';
import { ProviderCustom } from '@/shared';
import { UiHeader } from '@/components';

const roboto = Roboto({
  subsets: ['latin'],
  style: ['italic', 'normal'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--roboto'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='en' className={roboto.className}>
      <body>
        <ProviderCustom>
          <ProviderSetting>
            <UiSidebarLayout header={<UiHeader />} content={children} />
          </ProviderSetting>
        </ProviderCustom>
      </body>
    </html>
  );
}
